In [3]:
import os
os.chdir('/home/wiikai/factor')

import factorlab as lab

In [12]:
name = '20d_max_truerange'
df = lab.factor.read(name)
df = df.sort_index(ascending=False).unstack()
df.name = name
df

order_book_id  date
000001.XSHE    2024-07-01    0.030542
               2024-06-28    0.023807
               2024-06-27    0.024867
               2024-06-26    0.024867
               2024-06-25    0.024867
                               ...
689009.XSHG    2017-03-07         NaN
               2017-03-06         NaN
               2017-03-03         NaN
               2017-03-02         NaN
               2017-03-01         NaN
Name: 20d_max_truerange, Length: 9448117, dtype: float32

In [9]:
if name not in lab.factor.columns:
    lab.factor.add({name: df.dtype})
lab.factor.update(df)

In [10]:
lab.alpha.read(start='20231201', stop='20240101')

                          ff3_std_3m  ff3_std_down_3m  ff3_std_up_3m  \
order_book_id date
000001.XSHE   2023-12-01    0.052072         0.008037       0.088534
              2023-12-04    0.051865         0.008089       0.092645
              2023-12-05    0.051701         0.008019       0.087389
              2023-12-06    0.051698         0.008004       0.087320
              2023-12-07    0.051698         0.008053       0.092075
...                              ...              ...            ...
689009.XSHG   2023-12-25    0.015186         0.008373       0.009260
              2023-12-26    0.017093         0.011881       0.009801
              2023-12-27    0.017552         0.011933       0.010159
              2023-12-28    0.017552         0.011884       0.010298
              2023-12-29    0.017593         0.011945       0.010059

                          ff3_std_ud_3m    std_4m  capm_std_3m  turnover_cv  \
order_book_id date
000001.XSHE   2023-12-01       0.096571  0.045901     0.052258     0.239524
              2023-12-04       0.100734  0.045903     0.052062     0.250690
              2023-12-05       0.095408  0.045914     0.051990     0.242818
              2023-12-06       0.095323  0.045893     0.051994     0.245757
              2023-12-07       0.100127  0.045832     0.051993     0.250241
...                                 ...       ...          ...          ...
689009.XSHG   2023-12-25       0.017633  0.017891     0.015407     0.651351
              2023-12-26       0.021682  0.019616     0.017255     0.642012
              2023-12-27       0.022092  0.019964     0.017682     0.647495
              2023-12-28       0.022182  0.019973     0.017672     0.643479
              2023-12-29       0.022004  0.020045     0.017686     0.660410

                          mutilag_trend_pred  \
order_book_id date
000001.XSHE   2023-12-01            0.575255
              2023-12-04            0.177690
              2023-12-05            0.015054
              2023-12-06           -0.094684
              2023-12-07            0.071502
...                                      ...
689009.XSHG   2023-12-25            0.138383
              2023-12-26            0.188136
              2023-12-27            0.031321
              2023-12-28            0.005803
              2023-12-29            0.323237

                          information_distribution_uniformity  \
order_book_id date
000001.XSHE   2023-12-01                             0.071088
              2023-12-04                             0.070086
              2023-12-05                             0.069619
              2023-12-06                             0.083615
              2023-12-07                             0.086588
...                                                       ...
689009.XSHG   2023-12-25                             0.246438
              2023-12-26                             0.494839
              2023-12-27                             0.483312
              2023-12-28                             0.465676
              2023-12-29                             0.470212

                          smart_money_ratio  trend_fund_20d  \
order_book_id date
000001.XSHE   2023-12-01           0.999668    20489.297522
              2023-12-04           0.997678    18289.572473
              2023-12-05           0.999079    18429.672620
              2023-12-06           0.996818    17902.444397
              2023-12-07           0.993936    17897.312268
...                                     ...             ...
689009.XSHG   2023-12-25           0.994153    70505.678738
              2023-12-26           0.973414    80360.577518
              2023-12-27           0.978538    80736.805350
              2023-12-28           0.979874    81354.263412
              2023-12-29           0.982656    81229.672519

                          down_trend_volatility  fright_degree  \
order_book_id date
000001.XSHE   2023-12-01               0.482686       0.000013
              2023-12-04               0.464992       0.000012
              2023-12-05               0.520893       0.000012
              2023-12-06               0.471989       0.000013
              2023-12-07               0.529945       0.000013
...                                         ...            ...
689009.XSHG   2023-12-25               0.548800       0.000283
              2023-12-26               0.542794       0.000837
              2023-12-27               0.413262       0.001037
              2023-12-28               0.458675       0.001044
              2023-12-29               0.396471       0.001043

                          volume_peak_count  \
order_book_id date
000001.XSHE   2023-12-01               18.0
              2023-12-04               17.0
              2023-12-05               22.0
              2023-12-06               11.0
              2023-12-07               15.0
...                                     ...
689009.XSHG   2023-12-25               21.0
              2023-12-26                4.0
              2023-12-27               13.0
              2023-12-28               21.0
              2023-12-29               13.0

                          compound_industry_co_reverse_momemtum  20d_maxret  \
order_book_id date
000001.XSHE   2023-12-01                               0.049578    0.020038
              2023-12-04                               0.057596    0.009737
              2023-12-05                               0.069048    0.009737
              2023-12-06                               0.058916    0.009737
              2023-12-07                               0.059657    0.009737
...                                                         ...         ...
689009.XSHG   2023-12-25                               0.026926    0.020558
              2023-12-26                               0.046733    0.020558
              2023-12-27                               0.042682    0.037343
              2023-12-28                               0.027681    0.037343
              2023-12-29                               0.031717    0.037343

                          20d_top10_cum_ret   abnretd   abnvold
order_book_id date
000001.XSHE   2023-12-01           0.031527  0.011011  1.514995
              2023-12-04           0.008383  0.011011  1.517745
              2023-12-05           0.008383  0.011011  1.522143
              2023-12-06           0.015348  0.011011  1.525247
              2023-12-07           0.011446  0.011011  1.526578
...                                     ...       ...       ...
689009.XSHG   2023-12-25           0.064054  0.022295  3.905557
              2023-12-26           0.064054  0.022295  3.887591
              2023-12-27           0.109065  0.032138  3.880978
              2023-12-28           0.124905  0.032138  3.874393
              2023-12-29           0.129480  0.032138  3.868436

[110313 rows x 19 columns]

In [15]:
lab.factor.read(start='20231201', stop='20240101')

                          volume_weighted_price  fright_degree  ff3_std_3m  \
order_book_id date
000001.XSHE   2023-12-01               9.636755       0.000013    0.052072
              2023-12-04               9.641171       0.000012    0.051865
              2023-12-05               9.537874       0.000012    0.051701
              2023-12-06               9.483322       0.000013    0.051698
              2023-12-07               9.432522       0.000013    0.051698
...                                         ...            ...         ...
689009.XSHG   2023-12-25              30.535727       0.000283    0.015186
              2023-12-26              27.846027       0.000837    0.017093
              2023-12-27              28.273182       0.001037    0.017552
              2023-12-28              29.288090       0.001044    0.017552
              2023-12-29              29.817659       0.001043    0.017593

                          ff3_std_up_3m  ff3_std_down_3m  ff3_std_ud_3m  \
order_book_id date
000001.XSHE   2023-12-01       0.088534         0.008037       0.096571
              2023-12-04       0.092645         0.008089       0.100734
              2023-12-05       0.087389         0.008019       0.095408
              2023-12-06       0.087320         0.008004       0.095323
              2023-12-07       0.092075         0.008053       0.100127
...                                 ...              ...            ...
689009.XSHG   2023-12-25       0.009260         0.008373       0.017633
              2023-12-26       0.009801         0.011881       0.021682
              2023-12-27       0.010159         0.011933       0.022092
              2023-12-28       0.010298         0.011884       0.022182
              2023-12-29       0.010059         0.011945       0.022004

                            std_4m  capm_std_3m     trend_fund  \
order_book_id date
000001.XSHE   2023-12-01  0.045901     0.052258    3151.724365
              2023-12-04  0.045903     0.052062    2420.706055
              2023-12-05  0.045914     0.051990   12463.613281
              2023-12-06  0.045893     0.051994    6418.498047
              2023-12-07  0.045832     0.051993    4622.953613
...                            ...          ...            ...
689009.XSHG   2023-12-25  0.017891     0.015407   11638.900391
              2023-12-26  0.019616     0.017255  205917.203125
              2023-12-27  0.019964     0.017682   25307.021484
              2023-12-28  0.019973     0.017672   13206.194336
              2023-12-29  0.020045     0.017686    6576.562988

                          mutilag_trend_pred  ...  \
order_book_id date                            ...
000001.XSHE   2023-12-01            0.575255  ...
              2023-12-04            0.177690  ...
              2023-12-05            0.015054  ...
              2023-12-06           -0.094684  ...
              2023-12-07            0.071502  ...
...                                      ...  ...
689009.XSHG   2023-12-25            0.138383  ...
              2023-12-26            0.188136  ...
              2023-12-27            0.031321  ...
              2023-12-28            0.005803  ...
              2023-12-29            0.323237  ...

                          industry_co_20d_top5_cum_ret  \
order_book_id date
000001.XSHE   2023-12-01                      0.015483
              2023-12-04                      0.019959
              2023-12-05                      0.019959
              2023-12-06                      0.011113
              2023-12-07                      0.011113
...                                                ...
689009.XSHG   2023-12-25                     -0.000544
              2023-12-26                     -0.000544
              2023-12-27                      0.012055
              2023-12-28                      0.034350
              2023-12-29                      0.052629

                          industry_co_20d_max_truerange  \
order_book_id date
000001.XSHE   2023-12-01                      -0.011609
              2023-12-04                      -0.011609
              2023-12-05                      -0.011609
              2023-12-06                      -0.011609
              2023-12-07                      -0.011609
...                                                 ...
689009.XSHG   2023-12-25                      -0.021371
              2023-12-26                      -0.014888
              2023-12-27                      -0.014888
              2023-12-28                      -0.014888
              2023-12-29                      -0.014888

                          industry_co_20d_top5_cumret_weighted  \
order_book_id date
000001.XSHE   2023-12-01                              0.010348
              2023-12-04                              0.014348
              2023-12-05                              0.014348
              2023-12-06                              0.009239
              2023-12-07                              0.009239
...                                                        ...
689009.XSHG   2023-12-25                              0.000349
              2023-12-26                              0.000349
              2023-12-27                              0.009364
              2023-12-28                              0.020511
              2023-12-29                              0.031380

                          industry_co_20d_top5_cum_pricevolume_weighted  \
order_book_id date
000001.XSHE   2023-12-01                                       0.010348
              2023-12-04                                       0.014348
              2023-12-05                                       0.014348
              2023-12-06                                       0.009239
              2023-12-07                                       0.009239
...                                                                 ...
689009.XSHG   2023-12-25                                      -0.004654
              2023-12-26                                      -0.004654
              2023-12-27                                      -0.001817
              2023-12-28                                      -0.001817
              2023-12-29                                       0.004771

                          industry_co_20d_bottom15_cum_pricevolume_weighted  \
order_book_id date
000001.XSHE   2023-12-01                                          -0.039229
              2023-12-04                                          -0.043248
              2023-12-05                                          -0.054701
              2023-12-06                                          -0.049677
              2023-12-07                                          -0.050418
...                                                                     ...
689009.XSHG   2023-12-25                                          -0.031580
              2023-12-26                                          -0.051387
              2023-12-27                                          -0.044499
              2023-12-28                                          -0.029498
              2023-12-29                                          -0.026946

                          compound_industry_co_reverse_momemtum   abnretd  \
order_book_id date
000001.XSHE   2023-12-01                               0.049578  0.011011
              2023-12-04                               0.057596  0.011011
              2023-12-05                               0.069048  0.011011
              2023-12-06                               0.058916  0.011011
              2023-12-07                               0.059657  0.011011
...                                                         ...       ...
689009.XSHG   2023-12-25                               0.026926  0.022295
              2023-12-26                               0.046733  0.022295
              2023-12-27                               0.042682  0.032138
              2023-12-28                               0.027681  0.032138
              2023-12-29                               0.031717  0.032138

                          abneretm   abnvold    abnvolm
order_book_id date
000001.XSHE   2023-12-01  0.079897  1.514995  18.516031
              2023-12-04  0.080691  1.517745  18.446198
              2023-12-05  0.068222  1.522143  18.271791
              2023-12-06  0.060779  1.525247  18.425659
              2023-12-07  0.066844  1.526578  18.137541
...                            ...       ...        ...
689009.XSHG   2023-12-25  0.087874  3.905557  25.953300
              2023-12-26  0.126080  3.887591  26.367865
              2023-12-27  0.079875  3.880978  26.270153
              2023-12-28  0.086348  3.874393  25.949703
              2023-12-29  0.089736  3.868436  25.788078

[110313 rows x 31 columns]

In [4]:
lab.factor.read(start='20231201', stop='20240101').columns

Index(['volume_weighted_price', 'fright_degree', 'ff3_std_3m', 'ff3_std_up_3m',
       'ff3_std_down_3m', 'ff3_std_ud_3m', 'std_4m', 'capm_std_3m',
       'trend_fund', 'mutilag_trend_pred', 'turnover_cv',
       'information_distribution_uniformity', 'smart_money_ratio',
       'intraday_return_skew', 'intraday_return_kurt', 'trend_fund_20d',
       'volume_peak_count', '20d_maxret', '20d_top10_cum_ret',
       '20d_max_truerange', 'industry_co_20d_maxret',
       'industry_co_20d_top5_cum_ret', 'industry_co_20d_max_truerange',
       'industry_co_20d_top5_cumret_weighted',
       'industry_co_20d_top5_cum_pricevolume_weighted',
       'industry_co_20d_bottom15_cum_pricevolume_weighted',
       'compound_industry_co_reverse_momemtum', 'abnretd', 'abneretm',
       'abnvold', 'abnvolm', 'minute_str', 'str', '5minute_str'],
      dtype='object')

In [13]:
lab.factor.sub('attn_v2')